version: '3'
services:
  db:
    image: mysql:5.7
    restart: always
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ./mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=rude_pa55w0rd
      - MYSQL_DATABASE=db
      # - MYSQL_USER=user
      # - MYSQL_PASSWORD=pa55w0rd
