- hosts: dcos-cluster
  remote_user: centos
  become: false
  vars_files:
    - "../vars/{{ dcos_version }}.yaml"

  tasks:
  - name: Fetch DC/OS installer from Bootstrap Node
    get_url:
      url: http://{{ hostvars[groups['bootstrap'][0]].ansible_eth0['ipv4']['address'] }}/dcos_install.sh
      dest: "{{ tmp_dir }}"

- hosts: masters
  remote_user: centos
  become: true
  vars_files:
    - "../vars/{{ dcos_version }}.yaml"

  tasks:
  - name: Installation of master nodes
    async: 600
    poll: 0
    shell: "bash {{ tmp_dir }}/dcos_install.sh master"

- hosts: public-agents
  remote_user: centos
  become: true
  vars_files:
    - "../vars/{{ dcos_version }}.yaml"

  tasks:
  - name: Installation of public agents
    async: 600
    poll: 0
    shell: "bash {{ tmp_dir }}/dcos_install.sh slave_public"

- hosts: private-agents
  remote_user: centos
  become: true
  vars_files:
    - "../vars/{{ dcos_version }}.yaml"

  tasks:
  - name: Installation of private agents
    async: 600
    poll: 0
    shell: "bash {{ tmp_dir }}/dcos_install.sh slave"
